---

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "7x4B4rnJhZB438m9+BrBfQ=="
  evpn_overlay_peers:
      password: "Q4fqtbqcZ7oQuKfuWtNGRQ=="
  mlag_ipv4_underlay_peer:
      password: "4b21pAdCvWeAqpcKDFMdWw=="
# BGP Defaults
bgp_default_ipv4_unicast: false
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS-LAB
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # BGP ASN
    bgp_as: 65100
    # Definition of nodes contained in this group.
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: s1-spine1
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 1
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.10/24
    
    - name: s1-spine2
      id: 2
      mgmt_ip: 192.168.0.11/24

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS-LAB
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches:
      - s1-spine1
      - s1-spine2
    uplink_interfaces:
      - Ethernet2
      - Ethernet3
    mlag_interfaces:
      - Ethernet1
      - Ethernet6
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096

    # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC1_LEAFS_POD1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      filter:
        tenants:
          - CUSTOMER_A
        tags:
          - pod1
      nodes:
        - name: s1-leaf1
          id: 1
          mgmt_ip: 192.168.0.12/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
        - name: s1-leaf2
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
    - group: DC1_LEAFS_POD2
      bgp_as: 65102
      filter:
        tenants:
          - CUSTOMER_A
        tags:
          - pod2
      nodes:
        - name: s1-leaf3
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
        - name: s1-leaf4
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
        
